version: "3.9"

services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finkargo
      - LANG=en_US.utf8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 30s
      retries: 3
    volumes:
      - ../data/postgresql:/var/lib/postgresql
    ports:
      - 15432:5432
    networks:
      - net
  api:
    build: .
    environment:
      - POSTGRES_DB=finkargo
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - FLASK_APP=app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "flask db upgrade && flask run --host=0.0.0.0"
    networks:
      - net

networks:
  net:
    driver: bridge
    